base_url = "https://liul85.github.io"
title = "Liang's blog"

theme = "anpu"
taxonomies = [{ name = "categories" }, { name = "tags" }]

[markdown]
highlight_code = true

[extra]
anpu_menu_links = [
    { url = "$BASE_URL/tags/", name = "Tags" },
    { url = "https://twitter.com/liul85", name = "Twitter" },
]
