base_url = "https://blog.liangliu.me"
title = "Liang's blog"

theme = "bearblog"
compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
    { name = "tags", feed = true}
]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]
menu_links = [
    { url = "https://twitter.com/liul85", name = "twitter" },
]
