base_url = "https://liul85.github.io"
title = "Liang's blog"

theme = "prose"
compile_sass = true
generate_feed = true

[markdown]
highlight_code = true

[extra]
menu_links = [
    { url = "https://twitter.com/liul85", name = "twitter" },
]
